config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists do
    resources :bookmarks
    resources :reviews, only: :create
  end

  resources :bookmarks, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: {minimum: 6}
  validates :movie_id, uniqueness: {scope: :list_id, message: "has already been added to the list"}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
  has_many :reviews, dependent: :destroy

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  # before_destroy :check_for_bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

  # private
  # def check_for_bookmarks
  #    if bookmarks.exists?
  #      errors.add(:base, "cannot delete movie with bookmarks")
  #      throw(:abort)
  #    end
  #  end
end


  #   def prevent_destroy
  #   if !destroyed_by_parent
  #     self-errors[:base] << "you may not delete"
  #     return false
  #   end
  # end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), notice:"#{@bookmark} has been deleted"
  end


  private
  def bookmark_params
    params.require(:bookmark).permit(:comment,:movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = Bookmark.all
    @movies = Movie.all
  end


  private
  def list_params
    params.require(:list).permit(:name, :photo)
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @review = @list.reviews.build(review_params)
    if @review.save
      redirect_to list_path(@list), notice: "posted!"
    else
      redirect_to list_path(@list), alert: "review can't be blank!"
    end
  end


  private
  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/new.html.erb
<h1> add a bookmark </h1>
<!--navbar-->
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSz8sFwJDtQL4frmdgXIyKjnF_YyAr1gQ2BHw&s" />
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">My lists</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">New list</a>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>

<!--banner-->
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%=@list.image_url%>)">
  add a movie to the list: <%= @list.name %>
</div>

<h5>Add this movie:</h5>
<%= simple_form_for([@list, @bookmark]) do |l| %>
  <%= l.input :movie_id, collection: Movie.all, label_method: :title, prompt: "select a movie" %>
  <%= l.input :comment %>
  <%= l.button :submit, "add this movie to #{@list.name}" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<!--navbar-->

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="/lists">
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSz8sFwJDtQL4frmdgXIyKjnF_YyAr1gQ2BHw&s" />
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/lists">My lists</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/lists/new">New list</a>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>

<!--banner-->

<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://uploads.lebonbon.fr/source/2023/october/15064/-salome-rateau-1_1_2000.jpg)">
  Save any kind of movies
</div>

<!--second navbar-->
<div class="mylistadd">
  <h4>My lists:</h4>
    <%= link_to new_list_path, class: "btn btn-ghost" do %>
      Add a list
    <% end %>
</div>

<!--cards-->

<div class="cards">
  <% @lists.each do |list|%>
    <%# <%= cl_image_path(list.photo.key, height: 300, crop: :fill) if list.photo.attached? %>

    <!--what i had initially-->
    <%# <%= link_to list_path(list), class:"card-category", style:"background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(#{list.image_url})" do %>
    <!--trying to do image upldoad-->
    <% if list.photo.attached? %>
      <% background = cl_image_path(list.photo.key, height: 300, crop: :fill) %>
    <% else %>
      <% background = "https://hips.hearstapps.com/hmg-prod/images/classic-movies-1661199935.jpg?crop=1.00xw:1.00xh;0,0&resize=1200:*"%>
    <%end %>

    <%= link_to list_path(list), class:"card-category", style:"background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('#{background}')" do %>
      <%= list.name %>
    <% end %>
  <%end%>
</div>

app/views/lists/new.html.erb
<!--navbar-->

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="/lists">
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSz8sFwJDtQL4frmdgXIyKjnF_YyAr1gQ2BHw&s" />
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/lists">My lists</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/lists/new">New list</a>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>

<!--banner-->

<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://uploads.lebonbon.fr/source/2023/october/15064/-salome-rateau-1_1_2000.jpg)">
  Add a new list
</div>

<!--form-->
<h5>New list:</h5>
<%= simple_form_for(@list, html: {multipart: true}) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file, label: "upload a list image" %>
  <%= f.button :submit, "create list" %>
<% end %>

app/views/lists/show.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="/lists">
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSz8sFwJDtQL4frmdgXIyKjnF_YyAr1gQ2BHw&s" />
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/lists">My lists</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/lists/new">New list</a>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>

<!--banner-->
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill if @list.photo.attached? %>')">
  <%= @list.name %>
</div>

<%= link_to new_list_bookmark_path(@list) do %>
  <button class="btn btn-secondary">Add a movie to this lists</button>
<% end %>

<!--bookmarked movies-->
<!--1. find the bookmarks with my list id 2. need to find the bookmraks id_movies 3. need to display these movies-->
<div class="cards">
  <% @list.bookmarks.each do |bookmark| %>
      <!--display each movie in a nice grid-->
        <div class="card" style="width: 18rem;">
          <img src="<%= bookmark.movie.poster_url %>" class="card-img-top" alt="<%= bookmark.movie.title%>">
          <div class="card-body">
            <div class="d-flex justify-content-between align-items-center mb-2">
              <h5 class="card-title"><%= bookmark.movie.title %></h5>
              ★<%= bookmark.movie.rating%>
            </div>
            <p class="card-subtitle mb-2 text-body-secondary"><%= bookmark.movie.overview %></p>
            <div class="d-flex justify-content-between align-items-center mb-2">
              <p class="card-text t">
                  <i class="fa-solid fa-quote-left me-2"></i>
                  <em><%= bookmark.comment %></em>
              </p>
                <%= button_to "Delete", list_bookmark_path(@list, bookmark), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link text-danger p-0", form: { class: "d-inline" } %>
      </div>
          </div>
        </div>
  <% end %>
</div>

<!--REVIEW-->
<div id="reviewsbox" class="mt-5 mb-5 p-4 bg-light rounded shadow-sm">
  <h4 mt-4>Reviews of this list</h4>
  <div id="reviewcommentsbox">
    <% @list.reviews.each do |review|%>
      <ul>
        <li>🗨️<%= review.content %></li>
      </ul>
    <% end %>

  </div>
  <div id="reviewform">
    <%= form_with model: [@list, @list.reviews.build], local: true do |f| %>
      <%= f.text_area :content, class: "form-control", placeholder: "write your review"%>
      <%= f.submit "post review", class: "btn btn-primary mt-2"%>
    <% end %>
  </div>
</div>


<!--go back button-->

<%= link_to "/lists" do %>
  <button class="btn btn-primary mb-5">go back to all lists</button>
<% end %>